#!/usr/bin/env bun
import { mkdirSync, writeFileSync } from 'fs';
import { dirname, resolve } from 'path';

import {
  parseStockTakeWorkbook,
  STOCK_TAKE_LOCATION_MAP,
  sqlStringLiteral,
} from '../../src/lib/inventory/stocktake-reload';

interface CliOptions {
  xlsxPath: string;
  referenceDoc: string;
  outPath: string;
  metadataPath: string;
}

function parseArgs(argv: string[]): CliOptions {
  let xlsxPath = '';
  let referenceDoc = 'STOCK_TAKE_2026-02-26';
  let outPath = '';
  let metadataPath = '';

  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (!arg) continue;

    if (!arg.startsWith('--') && !xlsxPath) {
      xlsxPath = arg;
      continue;
    }

    if (arg === '--reference-doc') {
      referenceDoc = argv[++i] ?? referenceDoc;
      continue;
    }

    if (arg === '--out') {
      outPath = argv[++i] ?? outPath;
      continue;
    }

    if (arg === '--meta-out') {
      metadataPath = argv[++i] ?? metadataPath;
      continue;
    }
  }

  if (!xlsxPath) {
    throw new Error(
      'Usage: bun scripts/imports/generate-stocktake-reload-sql.ts <xlsx-path> [--reference-doc STOCK_TAKE_2026-02-26] [--out <sql-path>] [--meta-out <json-path>]'
    );
  }

  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  if (!outPath) {
    outPath = resolve(
      process.cwd(),
      'scripts',
      'imports',
      'reports',
      'generated',
      `stocktake-reload-${referenceDoc}-${timestamp}.sql`
    );
  } else {
    outPath = resolve(process.cwd(), outPath);
  }

  if (!metadataPath) {
    metadataPath = outPath.replace(/\.sql$/i, '.meta.json');
  } else {
    metadataPath = resolve(process.cwd(), metadataPath);
  }

  return { xlsxPath, referenceDoc, outPath, metadataPath };
}

function buildSql(options: CliOptions) {
  const parsed = parseStockTakeWorkbook(options.xlsxPath);

  const payload = parsed.rows.map((row, index) => ({
    row_num: index + 1,
    sku: row.sku,
    product_name: row.productName,
    input_location: row.location,
    uom: row.uom,
    qty: row.qoh,
  }));

  const payloadJson = JSON.stringify(payload);
  const payloadLiteral = sqlStringLiteral(payloadJson);
  const referenceLiteral = sqlStringLiteral(options.referenceDoc);
  const sourceLiteral = sqlStringLiteral(options.xlsxPath);
  const nowLiteral = sqlStringLiteral(new Date().toISOString());

  const locationValues = Object.entries(STOCK_TAKE_LOCATION_MAP)
    .map(([input, target]) => `  (${sqlStringLiteral(input)}, ${sqlStringLiteral(target)})`)
    .join(',\n');

  const expectedRows = parsed.totalAfterDedup;
  const expectedSkus = parsed.uniqueSkuCount;

  const sql = `-- Generated by scripts/imports/generate-stocktake-reload-sql.ts
-- Generated at: ${new Date().toISOString()}
-- Source workbook: ${options.xlsxPath}
-- Reference doc: ${options.referenceDoc}
-- Rows: raw=${parsed.totalRawRows}, valid=${parsed.totalValidRows}, dedup=${parsed.totalAfterDedup}
-- Unique SKUs: ${parsed.uniqueSkuCount}

SET statement_timeout = '10min';
SET lock_timeout = '30s';

CREATE TEMP TABLE tmp_stocktake_location_map (
  input_location text PRIMARY KEY,
  db_location text NOT NULL
) ON COMMIT DROP;

INSERT INTO tmp_stocktake_location_map (input_location, db_location) VALUES
${locationValues};

INSERT INTO core.stock_location (location_id, name, type, is_active, created_at, updated_at)
SELECT gen_random_uuid(), lm.db_location, 'internal', true, NOW(), NOW()
FROM tmp_stocktake_location_map lm
LEFT JOIN core.stock_location sl
  ON sl.name = lm.db_location
 AND sl.is_active = true
WHERE sl.location_id IS NULL;

CREATE TEMP TABLE tmp_stocktake_location_ids AS
SELECT sl.location_id, sl.name
FROM core.stock_location sl
JOIN tmp_stocktake_location_map lm ON lm.db_location = sl.name
WHERE sl.is_active = true;

DO $$
DECLARE
  v_locations integer;
BEGIN
  SELECT COUNT(*) INTO v_locations FROM tmp_stocktake_location_ids;
  IF v_locations <> 5 THEN
    RAISE EXCEPTION 'Expected 5 active stock-take locations, found %', v_locations;
  END IF;
END $$;

CREATE TEMP TABLE tmp_stocktake_input_raw (
  row_num integer,
  sku text,
  product_name text,
  input_location text,
  uom text,
  qty integer
) ON COMMIT DROP;

INSERT INTO tmp_stocktake_input_raw (row_num, sku, product_name, input_location, uom, qty)
SELECT row_num, sku, product_name, input_location, uom, qty
FROM jsonb_to_recordset(${payloadLiteral}::jsonb) AS x(
  row_num integer,
  sku text,
  product_name text,
  input_location text,
  uom text,
  qty integer
);

DO $$
DECLARE
  v_input_rows integer;
  v_bad_rows integer;
BEGIN
  SELECT COUNT(*) INTO v_input_rows FROM tmp_stocktake_input_raw;
  SELECT COUNT(*) INTO v_bad_rows
  FROM tmp_stocktake_input_raw
  WHERE COALESCE(NULLIF(BTRIM(sku), ''), '') = ''
     OR COALESCE(NULLIF(BTRIM(product_name), ''), '') = ''
     OR qty IS NULL
     OR qty <= 0;

  IF v_input_rows <> ${expectedRows} THEN
    RAISE EXCEPTION 'Input row count mismatch. expected=${expectedRows} actual=%', v_input_rows;
  END IF;

  IF v_bad_rows > 0 THEN
    RAISE EXCEPTION 'Input contains % invalid rows (blank SKU/name or qty<=0)', v_bad_rows;
  END IF;
END $$;

CREATE TEMP TABLE tmp_stocktake_input AS
SELECT
  i.row_num,
  BTRIM(i.sku) AS sku,
  BTRIM(i.product_name) AS product_name,
  BTRIM(i.input_location) AS input_location,
  BTRIM(i.uom) AS uom,
  i.qty,
  COALESCE(sl.location_id, sl_main.location_id) AS location_id
FROM tmp_stocktake_input_raw i
LEFT JOIN tmp_stocktake_location_map lm
  ON lm.input_location = i.input_location
LEFT JOIN core.stock_location sl
  ON sl.name = lm.db_location
 AND sl.is_active = true
LEFT JOIN core.stock_location sl_main
  ON sl_main.name = 'NXT Main Stock'
 AND sl_main.is_active = true;

DO $$
DECLARE
  v_null_locations integer;
  v_unique_skus integer;
BEGIN
  SELECT COUNT(*) INTO v_null_locations
  FROM tmp_stocktake_input
  WHERE location_id IS NULL;

  IF v_null_locations > 0 THEN
    RAISE EXCEPTION 'Resolved input has % rows with null location_id', v_null_locations;
  END IF;

  SELECT COUNT(DISTINCT sku) INTO v_unique_skus FROM tmp_stocktake_input;
  IF v_unique_skus <> ${expectedSkus} THEN
    RAISE EXCEPTION 'Unique SKU count mismatch. expected=${expectedSkus} actual=%', v_unique_skus;
  END IF;
END $$;

CREATE TEMP TABLE tmp_ref_impacted_products AS
SELECT DISTINCT supplier_product_id
FROM core.stock_movement
WHERE reference_doc = ${referenceLiteral};

CREATE TEMP TABLE tmp_stocktake_unmatched_recycle AS
SELECT sp.supplier_product_id
FROM core.supplier_product sp
JOIN core.supplier s ON s.supplier_id = sp.supplier_id
WHERE s.code = 'UNMATCHED'
  AND COALESCE(NULLIF(BTRIM(sp.attrs_json->>'source'), ''), '') = 'stock_take';

DO $$
DECLARE
  v_po_links integer;
  v_non_ref_movements integer;
BEGIN
  SELECT COUNT(*) INTO v_po_links
  FROM core.purchase_order_items poi
  WHERE poi.supplier_product_id IN (SELECT supplier_product_id FROM tmp_stocktake_unmatched_recycle);

  IF v_po_links > 0 THEN
    RAISE EXCEPTION 'Abort reset: % UNMATCHED stock_take products are referenced by purchase_order_items', v_po_links;
  END IF;

  SELECT COUNT(*) INTO v_non_ref_movements
  FROM core.stock_movement sm
  WHERE sm.supplier_product_id IN (SELECT supplier_product_id FROM tmp_stocktake_unmatched_recycle)
    AND sm.reference_doc IS DISTINCT FROM ${referenceLiteral};

  IF v_non_ref_movements > 0 THEN
    RAISE EXCEPTION 'Abort reset: % UNMATCHED stock_take products have non-stocktake movement references', v_non_ref_movements;
  END IF;
END $$;

DELETE FROM core.stock_movement
WHERE reference_doc = ${referenceLiteral};

DELETE FROM core.stock_on_hand soh
USING tmp_ref_impacted_products p, tmp_stocktake_location_ids l
WHERE soh.supplier_product_id = p.supplier_product_id
  AND soh.location_id = l.location_id;

DELETE FROM core.supplier_product sp
USING tmp_stocktake_unmatched_recycle r
WHERE sp.supplier_product_id = r.supplier_product_id;

INSERT INTO core.supplier (
  supplier_id,
  name,
  code,
  active,
  default_currency,
  created_at,
  updated_at
)
SELECT gen_random_uuid(), 'UNMATCHED', 'UNMATCHED', true, 'ZAR', NOW(), NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM core.supplier WHERE code = 'UNMATCHED'
);

CREATE TEMP TABLE tmp_unmatched_supplier AS
SELECT supplier_id
FROM core.supplier
WHERE code = 'UNMATCHED'
ORDER BY created_at ASC
LIMIT 1;

DO $$
DECLARE
  v_unmatched_supplier integer;
BEGIN
  SELECT COUNT(*) INTO v_unmatched_supplier FROM tmp_unmatched_supplier;
  IF v_unmatched_supplier <> 1 THEN
    RAISE EXCEPTION 'Expected a single UNMATCHED supplier id context row, found %', v_unmatched_supplier;
  END IF;
END $$;

CREATE TEMP TABLE tmp_primary_match AS
SELECT
  i.row_num,
  i.sku,
  i.product_name,
  i.input_location,
  i.uom,
  i.qty,
  i.location_id,
  m.supplier_product_id,
  m.supplier_id
FROM tmp_stocktake_input i
LEFT JOIN LATERAL (
  SELECT sp.supplier_product_id, sp.supplier_id
  FROM core.supplier_product sp
  JOIN core.supplier s ON s.supplier_id = sp.supplier_id
  WHERE sp.supplier_sku = i.sku
    AND sp.is_active = true
    AND s.code <> 'UNMATCHED'
  ORDER BY sp.last_seen_at DESC NULLS LAST, sp.updated_at DESC NULLS LAST
  LIMIT 1
) m ON TRUE;

CREATE TEMP TABLE tmp_unmatched_distinct AS
SELECT DISTINCT ON (sku)
  sku,
  product_name,
  uom
FROM tmp_primary_match
WHERE supplier_product_id IS NULL
ORDER BY sku, row_num;

INSERT INTO core.supplier_product (
  supplier_product_id,
  supplier_id,
  supplier_sku,
  name_from_supplier,
  uom,
  attrs_json,
  is_active,
  is_new,
  first_seen_at,
  last_seen_at,
  created_at,
  updated_at
)
SELECT
  gen_random_uuid(),
  us.supplier_id,
  u.sku,
  u.product_name,
  CASE WHEN LOWER(u.uom) = 'm' THEN 'm' ELSE 'each' END,
  jsonb_build_object(
    'source', 'stock_take',
    'cost_excluding', 0,
    'description', u.product_name,
    'source_file', ${sourceLiteral},
    'source_generated_at', ${nowLiteral}
  ),
  true,
  true,
  NOW(),
  NOW(),
  NOW(),
  NOW()
FROM tmp_unmatched_distinct u
CROSS JOIN tmp_unmatched_supplier us
ON CONFLICT ON CONSTRAINT supplier_product_supplier_id_supplier_sku_key DO UPDATE
SET
  name_from_supplier = COALESCE(NULLIF(BTRIM(core.supplier_product.name_from_supplier), ''), EXCLUDED.name_from_supplier),
  attrs_json = CASE
    WHEN COALESCE(NULLIF(BTRIM(core.supplier_product.attrs_json->>'description'), ''), '') = ''
      THEN jsonb_set(COALESCE(core.supplier_product.attrs_json, '{}'::jsonb), '{description}', to_jsonb(EXCLUDED.name_from_supplier), true)
    ELSE core.supplier_product.attrs_json
  END,
  is_active = true,
  last_seen_at = NOW(),
  updated_at = NOW();

CREATE TEMP TABLE tmp_resolved_import AS
SELECT
  m.row_num,
  m.sku,
  m.product_name,
  m.input_location,
  m.location_id,
  m.qty,
  COALESCE(m.supplier_product_id, sp_u.supplier_product_id) AS supplier_product_id,
  CASE
    WHEN m.supplier_product_id IS NULL THEN 0::numeric
    ELSE ph.price
  END AS unit_cost
FROM tmp_primary_match m
LEFT JOIN tmp_unmatched_supplier us ON TRUE
LEFT JOIN core.supplier_product sp_u
  ON m.supplier_product_id IS NULL
 AND sp_u.supplier_id = us.supplier_id
 AND sp_u.supplier_sku = m.sku
LEFT JOIN LATERAL (
  SELECT ph.price
  FROM core.price_history ph
  WHERE ph.supplier_product_id = m.supplier_product_id
    AND ph.is_current = true
  ORDER BY ph.valid_from DESC
  LIMIT 1
) ph ON TRUE;

DO $$
DECLARE
  v_missing_products integer;
BEGIN
  SELECT COUNT(*) INTO v_missing_products
  FROM tmp_resolved_import
  WHERE supplier_product_id IS NULL;

  IF v_missing_products > 0 THEN
    RAISE EXCEPTION 'Resolved import has % rows with null supplier_product_id', v_missing_products;
  END IF;
END $$;

WITH preferred_name AS (
  SELECT supplier_product_id, MIN(product_name) AS product_name
  FROM tmp_resolved_import
  GROUP BY supplier_product_id
)
UPDATE core.supplier_product sp
SET
  name_from_supplier = CASE
    WHEN COALESCE(NULLIF(BTRIM(sp.name_from_supplier), ''), '') = '' THEN pn.product_name
    ELSE sp.name_from_supplier
  END,
  attrs_json = CASE
    WHEN COALESCE(NULLIF(BTRIM(sp.attrs_json->>'description'), ''), '') = ''
      THEN jsonb_set(COALESCE(sp.attrs_json, '{}'::jsonb), '{description}', to_jsonb(pn.product_name), true)
    ELSE sp.attrs_json
  END,
  updated_at = NOW()
FROM preferred_name pn
WHERE sp.supplier_product_id = pn.supplier_product_id
  AND COALESCE(NULLIF(BTRIM(pn.product_name), ''), '') <> ''
  AND (
    COALESCE(NULLIF(BTRIM(sp.name_from_supplier), ''), '') = ''
    OR COALESCE(NULLIF(BTRIM(sp.attrs_json->>'description'), ''), '') = ''
  );

INSERT INTO core.stock_on_hand (
  soh_id,
  location_id,
  supplier_product_id,
  qty,
  unit_cost,
  as_of_ts,
  source,
  created_at
)
SELECT
  gen_random_uuid(),
  r.location_id,
  r.supplier_product_id,
  r.qty,
  r.unit_cost,
  NOW(),
  'import',
  NOW()
FROM tmp_resolved_import r
ON CONFLICT ON CONSTRAINT stock_on_hand_location_id_supplier_product_id_key DO UPDATE
SET
  qty = EXCLUDED.qty,
  unit_cost = COALESCE(EXCLUDED.unit_cost, core.stock_on_hand.unit_cost),
  as_of_ts = NOW();

INSERT INTO core.stock_movement (
  movement_id,
  movement_type,
  supplier_product_id,
  location_id,
  qty,
  reference_doc,
  notes,
  movement_ts,
  created_at
)
SELECT
  gen_random_uuid(),
  'ADJUSTMENT',
  r.supplier_product_id,
  r.location_id,
  r.qty,
  ${referenceLiteral},
  'Physical stock take count (reset + reapply)',
  NOW(),
  NOW()
FROM tmp_resolved_import r;

DO $$
DECLARE
  v_expected_rows integer;
  v_movement_rows integer;
  v_blank_name integer;
  v_blank_desc integer;
BEGIN
  SELECT COUNT(*) INTO v_expected_rows FROM tmp_resolved_import;
  SELECT COUNT(*) INTO v_movement_rows
  FROM core.stock_movement
  WHERE reference_doc = ${referenceLiteral};

  IF v_expected_rows <> v_movement_rows THEN
    RAISE EXCEPTION 'Movement row mismatch after reload. expected=% actual=%', v_expected_rows, v_movement_rows;
  END IF;

  SELECT COUNT(*) INTO v_blank_name
  FROM public.inventory_items iv
  WHERE COALESCE(NULLIF(BTRIM(iv.name), ''), '') = '';

  IF v_blank_name > 0 THEN
    RAISE EXCEPTION 'Post-check failed: % blank inventory item names remain', v_blank_name;
  END IF;

  WITH impacted AS (
    SELECT DISTINCT supplier_product_id
    FROM core.stock_movement
    WHERE reference_doc = ${referenceLiteral}
  )
  SELECT COUNT(*) INTO v_blank_desc
  FROM impacted i
  JOIN core.supplier_product sp ON sp.supplier_product_id = i.supplier_product_id
  JOIN public.inventory_items iv
    ON iv.sku = sp.supplier_sku
   AND iv.supplier_id::text = sp.supplier_id::text
  WHERE COALESCE(NULLIF(BTRIM(iv.description), ''), '') = '';

  IF v_blank_desc > 0 THEN
    RAISE EXCEPTION 'Post-check failed: % stock-take impacted inventory rows have blank description', v_blank_desc;
  END IF;
END $$;

SELECT
  ${referenceLiteral} AS reference_doc,
  ${expectedRows}::integer AS expected_dedup_rows,
  (SELECT COUNT(*) FROM tmp_stocktake_input_raw) AS input_rows,
  (SELECT COUNT(*) FROM tmp_resolved_import) AS imported_rows,
  (SELECT COUNT(*) FROM core.stock_movement WHERE reference_doc = ${referenceLiteral}) AS movement_rows,
  (SELECT COUNT(DISTINCT supplier_product_id) FROM core.stock_movement WHERE reference_doc = ${referenceLiteral}) AS movement_distinct_products;
`;

  return {
    parsed,
    payloadRows: payload.length,
    sql,
  };
}

function main() {
  const options = parseArgs(process.argv.slice(2));
  const built = buildSql(options);

  mkdirSync(dirname(options.outPath), { recursive: true });
  mkdirSync(dirname(options.metadataPath), { recursive: true });

  writeFileSync(options.outPath, built.sql);

  const meta = {
    generatedAt: new Date().toISOString(),
    sourceFile: options.xlsxPath,
    referenceDoc: options.referenceDoc,
    outPath: options.outPath,
    totalRawRows: built.parsed.totalRawRows,
    totalValidRows: built.parsed.totalValidRows,
    totalAfterDedup: built.parsed.totalAfterDedup,
    duplicatesResolved: built.parsed.duplicatesResolved,
    uniqueSkuCount: built.parsed.uniqueSkuCount,
    payloadRows: built.payloadRows,
    locationBreakdown: built.parsed.locationBreakdown,
    headers: built.parsed.headerMap,
  };

  writeFileSync(options.metadataPath, `${JSON.stringify(meta, null, 2)}\n`);

  console.log('Generated stock-take reload SQL and metadata');
  console.log(`  SQL:  ${options.outPath}`);
  console.log(`  Meta: ${options.metadataPath}`);
  console.log(`  Rows: raw=${meta.totalRawRows}, valid=${meta.totalValidRows}, dedup=${meta.totalAfterDedup}, unique_sku=${meta.uniqueSkuCount}`);
}

main();
