version: "3.9"

services:
  app:
    build:
      context: .
      target: runner
    image: mantisnxt-app:latest
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
    depends_on: []
    restart: unless-stopped
