ALTER TABLE organization ENABLE ROW LEVEL SECURITY;
ALTER TABLE profile ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_log ENABLE ROW LEVEL SECURITY;

ALTER TABLE supplier ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_item ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchase_order ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchase_order_item ENABLE ROW LEVEL SECURITY;

ALTER TABLE ai_conversation ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_message ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_dataset ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_prompt_template ENABLE ROW LEVEL SECURITY;

ALTER TABLE customer ENABLE ROW LEVEL SECURITY;
ALTER TABLE customer_interaction ENABLE ROW LEVEL SECURITY;
ALTER TABLE support_ticket ENABLE ROW LEVEL SECURITY;
ALTER TABLE ticket_comment ENABLE ROW LEVEL SECURITY;

ALTER TABLE integration_connector ENABLE ROW LEVEL SECURITY;
ALTER TABLE data_import ENABLE ROW LEVEL SECURITY;
ALTER TABLE automation_pipeline ENABLE ROW LEVEL SECURITY;
ALTER TABLE pipeline_execution ENABLE ROW LEVEL SECURITY;
ALTER TABLE integration_log ENABLE ROW LEVEL SECURITY;

ALTER TABLE dashboard ENABLE ROW LEVEL SECURITY;
ALTER TABLE widget ENABLE ROW LEVEL SECURITY;
ALTER TABLE widget_data_cache ENABLE ROW LEVEL SECURITY;
ALTER TABLE notification ENABLE ROW LEVEL SECURITY;
ALTER TABLE system_metric ENABLE ROW LEVEL SECURITY;
ALTER TABLE dashboard_favorite ENABLE ROW LEVEL SECURITY;
ALTER TABLE dashboard_share ENABLE ROW LEVEL SECURITY;
ALTER TABLE alert_rule ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION auth.user_org_id()
RETURNS uuid
LANGUAGE sql
SECURITY DEFINER
STABLE
AS $$
    SELECT org_id FROM profile WHERE id = auth.uid();
$$;

CREATE OR REPLACE FUNCTION auth.user_role()
RETURNS user_role
LANGUAGE sql
SECURITY DEFINER
STABLE
AS $$
    SELECT role FROM profile WHERE id = auth.uid();
$$;

CREATE OR REPLACE FUNCTION auth.is_admin()
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
STABLE
AS $$
    SELECT EXISTS (
        SELECT 1 FROM profile
        WHERE id = auth.uid() AND role = 'admin'
    );
$$;

CREATE OR REPLACE FUNCTION auth.has_role(allowed_roles text[])
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
STABLE
AS $$
    SELECT EXISTS (
        SELECT 1 FROM profile
        WHERE id = auth.uid() AND role = ANY(allowed_roles::user_role[])
    );
$$;

