version: "3.9"

services:
  app:
    build:
      context: .
      target: builder
    image: mantisnxt-app-dev:latest
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NEXT_TELEMETRY_DISABLED: "1"
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    restart: unless-stopped
