const { Pool } = require('pg')

// Database configuration
const pool = new Pool({
  host: '62.169.20.53',
  port: 6600,
  database: 'nxtprod-db_001',
  user: 'nxtdb_admin',
  password: 'P@33w0rd-1',
})

// Your 22 suppliers with enhanced mock data
const suppliers = [
  {
    id: 'cd8fa19a-2749-47ed-b932-d6b28fe9e149',
    name: 'BK Percussion',
    supplier_code: 'BKPRC',
    company_name: 'BK Percussion (Pty) Ltd',
    email: 'sarah@bkpercussion.co.za',
    phone: '+27 11 234 5678',
    contact_person: 'Sarah Mitchell',
    address: '123 Music Street, Johannesburg, Gauteng 2000',
    website: 'https://www.bkpercussion.co.za',
    tax_id: '9012345678',
    payment_terms: 'Net 30',
    primary_category: 'Musical Instruments',
    geographic_region: 'Gauteng',
    preferred_supplier: true,
    bee_level: 'Level 4',
    local_content_percentage: 75,
    status: 'active',
    performance_tier: 'tier_1',
    spend_last_12_months: '2850000.00',
    rating: '4.70'
  },
  {
    id: '06de9fb9-252b-4273-97eb-00140f03af55',
    name: 'BC Electronics',
    supplier_code: 'BCELEC',
    company_name: 'BC Electronics (Pty) Ltd',
    email: 'david@bcelectronics.co.za',
    phone: '+27 21 345 6789',
    contact_person: 'David Chen',
    address: '456 Tech Avenue, Cape Town, Western Cape 8001',
    website: 'https://www.bcelectronics.co.za',
    tax_id: '9123456789',
    payment_terms: 'Net 30',
    primary_category: 'Electronics',
    geographic_region: 'Western Cape',
    preferred_supplier: true,
    bee_level: 'Level 3',
    local_content_percentage: 60,
    status: 'active',
    performance_tier: 'tier_2',
    spend_last_12_months: '1890000.00',
    rating: '4.50'
  },
  {
    id: '48328342-709d-42f0-82aa-85395022e8f7',
    name: 'Legacy Brands',
    supplier_code: 'LEGACY',
    company_name: 'Legacy Brands (Pty) Ltd',
    email: 'mike@legacybrands.co.za',
    phone: '+27 31 456 7890',
    contact_person: 'Mike Rodriguez',
    address: '789 Guitar Lane, Durban, KwaZulu-Natal 4000',
    website: 'https://www.legacybrands.co.za',
    tax_id: '9234567890',
    payment_terms: 'Net 45',
    primary_category: 'Musical Instruments',
    geographic_region: 'KwaZulu-Natal',
    preferred_supplier: false,
    bee_level: 'Level 2',
    local_content_percentage: 45,
    status: 'active',
    performance_tier: 'tier_3',
    spend_last_12_months: '1250000.00',
    rating: '4.30'
  },
  {
    id: 'fc6cb400-493c-400d-a534-4f10dcf66f07',
    name: 'Alpha Technologies',
    supplier_code: 'ALPHAT',
    company_name: 'Alpha Technologies (Pty) Ltd',
    email: 'info@alphatech.co.za',
    phone: '+27 11 987 6543',
    contact_person: 'Lisa Thompson',
    address: '321 Innovation Drive, Pretoria, Gauteng 0001',
    website: 'https://www.alphatech.co.za',
    tax_id: '9345678901',
    payment_terms: 'Net 30',
    primary_category: 'Technology',
    geographic_region: 'Gauteng',
    preferred_supplier: true,
    bee_level: 'Level 1',
    local_content_percentage: 85,
    status: 'active',
    performance_tier: 'tier_1',
    spend_last_12_months: '3200000.00',
    rating: '4.80'
  },
  {
    id: 'ecc30b28-10eb-4719-9bce-8d7267c7d37d',
    name: 'Music Power',
    supplier_code: 'MUSPOW',
    company_name: 'Music Power (Pty) Ltd',
    email: 'sales@musicpower.co.za',
    phone: '+27 21 555 1234',
    contact_person: 'John Williams',
    address: '654 Sound Street, Cape Town, Western Cape 8002',
    website: 'https://www.musicpower.co.za',
    tax_id: '9456789012',
    payment_terms: 'Net 30',
    primary_category: 'Audio Equipment',
    geographic_region: 'Western Cape',
    preferred_supplier: false,
    bee_level: 'Level 3',
    local_content_percentage: 55,
    status: 'active',
    performance_tier: 'tier_2',
    spend_last_12_months: '1750000.00',
    rating: '4.40'
  },
  {
    id: '11111111-1111-1111-1111-111111111111',
    name: 'Viva Afrika',
    supplier_code: 'VIVAAF',
    company_name: 'Viva Afrika (Pty) Ltd',
    email: 'contact@vivaafrika.co.za',
    phone: '+27 31 333 4444',
    contact_person: 'Nomsa Mbeki',
    address: '987 Heritage Road, Durban, KwaZulu-Natal 4001',
    website: 'https://www.vivaafrika.co.za',
    tax_id: '9567890123',
    payment_terms: 'Net 30',
    primary_category: 'Cultural Instruments',
    geographic_region: 'KwaZulu-Natal',
    preferred_supplier: true,
    bee_level: 'Level 1',
    local_content_percentage: 95,
    status: 'active',
    performance_tier: 'tier_1',
    spend_last_12_months: '980000.00',
    rating: '4.60'
  },
  {
    id: '22222222-2222-2222-2222-222222222222',
    name: 'Audiolite',
    supplier_code: 'AUDIOL',
    company_name: 'Audiolite (Pty) Ltd',
    email: 'info@audiolite.co.za',
    phone: '+27 11 777 8888',
    contact_person: 'Peter van der Merwe',
    address: '147 Audio Avenue, Johannesburg, Gauteng 2001',
    website: 'https://www.audiolite.co.za',
    tax_id: '9678901234',
    payment_terms: 'Net 45',
    primary_category: 'Lighting & Audio',
    geographic_region: 'Gauteng',
    preferred_supplier: false,
    bee_level: 'Level 4',
    local_content_percentage: 40,
    status: 'active',
    performance_tier: 'tier_2',
    spend_last_12_months: '1450000.00',
    rating: '4.20'
  },
  {
    id: '33333333-3333-3333-3333-333333333333',
    name: 'Tuerk Multimedia',
    supplier_code: 'TURKMM',
    company_name: 'Tuerk Multimedia (Pty) Ltd',
    email: 'sales@tuerkmultimedia.co.za',
    phone: '+27 21 999 0000',
    contact_person: 'Hans Mueller',
    address: '258 Media Street, Cape Town, Western Cape 8003',
    website: 'https://www.tuerkmultimedia.co.za',
    tax_id: '9789012345',
    payment_terms: 'Net 30',
    primary_category: 'Multimedia Systems',
    geographic_region: 'Western Cape',
    preferred_supplier: true,
    bee_level: 'Level 2',
    local_content_percentage: 65,
    status: 'active',
    performance_tier: 'tier_1',
    spend_last_12_months: '2100000.00',
    rating: '4.70'
  },
  {
    id: '44444444-4444-4444-4444-444444444444',
    name: 'Tuerk Technologies',
    supplier_code: 'TURKTE',
    company_name: 'Tuerk Technologies (Pty) Ltd',
    email: 'tech@tuerktech.co.za',
    phone: '+27 21 111 2222',
    contact_person: 'Klaus Schmidt',
    address: '369 Tech Park, Cape Town, Western Cape 8004',
    website: 'https://www.tuerktech.co.za',
    tax_id: '9890123456',
    payment_terms: 'Net 30',
    primary_category: 'Technology Solutions',
    geographic_region: 'Western Cape',
    preferred_supplier: true,
    bee_level: 'Level 3',
    local_content_percentage: 70,
    status: 'active',
    performance_tier: 'tier_1',
    spend_last_12_months: '2750000.00',
    rating: '4.65'
  },
  {
    id: '55555555-5555-5555-5555-555555555555',
    name: 'Sonic Informed',
    supplier_code: 'SONINF',
    company_name: 'Sonic Informed (Pty) Ltd',
    email: 'info@sonicinformed.co.za',
    phone: '+27 11 444 5555',
    contact_person: 'Amy Johnson',
    address: '741 Sound Plaza, Johannesburg, Gauteng 2002',
    website: 'https://www.sonicinformed.co.za',
    tax_id: '9901234567',
    payment_terms: 'Net 30',
    primary_category: 'Audio Technology',
    geographic_region: 'Gauteng',
    preferred_supplier: false,
    bee_level: 'Level 4',
    local_content_percentage: 50,
    status: 'active',
    performance_tier: 'tier_2',
    spend_last_12_months: '1320000.00',
    rating: '4.35'
  },
  {
    id: '66666666-6666-6666-6666-666666666666',
    name: 'Stage Audio Works',
    supplier_code: 'STGAW',
    company_name: 'Stage Audio Works (Pty) Ltd',
    email: 'contact@stageaudio.co.za',
    phone: '+27 31 666 7777',
    contact_person: 'Trevor Smith',
    address: '852 Stage Street, Durban, KwaZulu-Natal 4002',
    website: 'https://www.stageaudio.co.za',
    tax_id: '9012345679',
    payment_terms: 'Net 45',
    primary_category: 'Stage Equipment',
    geographic_region: 'KwaZulu-Natal',
    preferred_supplier: true,
    bee_level: 'Level 2',
    local_content_percentage: 60,
    status: 'active',
    performance_tier: 'tier_2',
    spend_last_12_months: '1680000.00',
    rating: '4.45'
  },
  {
    id: '77777777-7777-7777-7777-777777777777',
    name: 'Stage One Distribution',
    supplier_code: 'STGONE',
    company_name: 'Stage One Distribution (Pty) Ltd',
    email: 'orders@stageone.co.za',
    phone: '+27 21 888 9999',
    contact_person: 'Michelle Brown',
    address: '963 Distribution Drive, Cape Town, Western Cape 8005',
    website: 'https://www.stageone.co.za',
    tax_id: '9123456780',
    payment_terms: 'Net 30',
    primary_category: 'Equipment Distribution',
    geographic_region: 'Western Cape',
    preferred_supplier: true,
    bee_level: 'Level 3',
    local_content_percentage: 45,
    status: 'active',
    performance_tier: 'tier_1',
    spend_last_12_months: '2900000.00',
    rating: '4.75'
  },
  {
    id: '88888888-8888-8888-8888-888888888888',
    name: 'Yamaha Music South Africa',
    supplier_code: 'YAMZA',
    company_name: 'Yamaha Music South Africa (Pty) Ltd',
    email: 'info@yamaha.co.za',
    phone: '+27 11 000 1111',
    contact_person: 'Hiroshi Tanaka',
    address: '159 Music Boulevard, Johannesburg, Gauteng 2003',
    website: 'https://www.yamaha.co.za',
    tax_id: '9234567891',
    payment_terms: 'Net 30',
    primary_category: 'Musical Instruments',
    geographic_region: 'Gauteng',
    preferred_supplier: true,
    bee_level: 'Level 4',
    local_content_percentage: 30,
    status: 'active',
    performance_tier: 'tier_1',
    spend_last_12_months: '4200000.00',
    rating: '4.90'
  },
  {
    id: '99999999-9999-9999-9999-999999999999',
    name: 'AV Distribution',
    supplier_code: 'AVDIST',
    company_name: 'AV Distribution (Pty) Ltd',
    email: 'sales@avdist.co.za',
    phone: '+27 31 222 3333',
    contact_person: 'Robert Davis',
    address: '753 AV Street, Durban, KwaZulu-Natal 4003',
    website: 'https://www.avdist.co.za',
    tax_id: '9345678902',
    payment_terms: 'Net 30',
    primary_category: 'Audio Visual',
    geographic_region: 'KwaZulu-Natal',
    preferred_supplier: false,
    bee_level: 'Level 3',
    local_content_percentage: 55,
    status: 'active',
    performance_tier: 'tier_2',
    spend_last_12_months: '1590000.00',
    rating: '4.25'
  },
  {
    id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    name: 'Sennheiser South Africa',
    supplier_code: 'SENNZA',
    company_name: 'Sennheiser South Africa (Pty) Ltd',
    email: 'info@sennheiser.co.za',
    phone: '+27 21 555 6666',
    contact_person: 'Wolfgang Weber',
    address: '864 Audio Technology Park, Cape Town, Western Cape 8006',
    website: 'https://www.sennheiser.co.za',
    tax_id: '9456789013',
    payment_terms: 'Net 30',
    primary_category: 'Professional Audio',
    geographic_region: 'Western Cape',
    preferred_supplier: true,
    bee_level: 'Level 4',
    local_content_percentage: 25,
    status: 'active',
    performance_tier: 'tier_1',
    spend_last_12_months: '3500000.00',
    rating: '4.85'
  },
  {
    id: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
    name: 'Planetworld',
    supplier_code: 'PLANET',
    company_name: 'Planetworld (Pty) Ltd',
    email: 'contact@planetworld.co.za',
    phone: '+27 11 777 8888',
    contact_person: 'Sarah Wilson',
    address: '975 Planet Avenue, Johannesburg, Gauteng 2004',
    website: 'https://www.planetworld.co.za',
    tax_id: '9567890124',
    payment_terms: 'Net 45',
    primary_category: 'Entertainment Systems',
    geographic_region: 'Gauteng',
    preferred_supplier: false,
    bee_level: 'Level 2',
    local_content_percentage: 65,
    status: 'active',
    performance_tier: 'tier_2',
    spend_last_12_months: '1200000.00',
    rating: '4.15'
  },
  {
    id: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
    name: 'MD Distribution',
    supplier_code: 'MDDIST',
    company_name: 'MD Distribution (Pty) Ltd',
    email: 'info@mddist.co.za',
    phone: '+27 31 999 0000',
    contact_person: 'Michael Davies',
    address: '186 Distribution Way, Durban, KwaZulu-Natal 4004',
    website: 'https://www.mddist.co.za',
    tax_id: '9678901235',
    payment_terms: 'Net 30',
    primary_category: 'Music Distribution',
    geographic_region: 'KwaZulu-Natal',
    preferred_supplier: true,
    bee_level: 'Level 3',
    local_content_percentage: 70,
    status: 'active',
    performance_tier: 'tier_2',
    spend_last_12_months: '1850000.00',
    rating: '4.55'
  },
  {
    id: 'dddddddd-dddd-dddd-dddd-dddddddddddd',
    name: 'Rockit Distribution',
    supplier_code: 'ROCKIT',
    company_name: 'Rockit Distribution (Pty) Ltd',
    email: 'sales@rockit.co.za',
    phone: '+27 21 111 2222',
    contact_person: 'Rachel Green',
    address: '297 Rock Street, Cape Town, Western Cape 8007',
    website: 'https://www.rockit.co.za',
    tax_id: '9789012346',
    payment_terms: 'Net 30',
    primary_category: 'Music Equipment',
    geographic_region: 'Western Cape',
    preferred_supplier: false,
    bee_level: 'Level 4',
    local_content_percentage: 35,
    status: 'active',
    performance_tier: 'tier_3',
    spend_last_12_months: '1100000.00',
    rating: '4.10'
  },
  {
    id: 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee',
    name: 'Rolling Thunder',
    supplier_code: 'RLTHDR',
    company_name: 'Rolling Thunder (Pty) Ltd',
    email: 'info@rollingthunder.co.za',
    phone: '+27 11 333 4444',
    contact_person: 'Thunder Jackson',
    address: '408 Thunder Road, Johannesburg, Gauteng 2005',
    website: 'https://www.rollingthunder.co.za',
    tax_id: '9890123457',
    payment_terms: 'Net 45',
    primary_category: 'Live Sound',
    geographic_region: 'Gauteng',
    preferred_supplier: true,
    bee_level: 'Level 1',
    local_content_percentage: 80,
    status: 'active',
    performance_tier: 'tier_1',
    spend_last_12_months: '2400000.00',
    rating: '4.65'
  },
  {
    id: 'ffffffff-ffff-ffff-ffff-ffffffffffff',
    name: 'Global Music',
    supplier_code: 'GLOMUS',
    company_name: 'Global Music (Pty) Ltd',
    email: 'contact@globalmusic.co.za',
    phone: '+27 31 555 6666',
    contact_person: 'Global Manager',
    address: '519 Global Plaza, Durban, KwaZulu-Natal 4005',
    website: 'https://www.globalmusic.co.za',
    tax_id: '9901234568',
    payment_terms: 'Net 30',
    primary_category: 'Music Retail',
    geographic_region: 'KwaZulu-Natal',
    preferred_supplier: false,
    bee_level: 'Level 3',
    local_content_percentage: 50,
    status: 'active',
    performance_tier: 'tier_2',
    spend_last_12_months: '1350000.00',
    rating: '4.30'
  },
  {
    id: 'a1a1a1a1-a1a1-a1a1-a1a1-a1a1a1a1a1a1',
    name: 'Audiosure',
    supplier_code: 'AUDSURE',
    company_name: 'Audiosure (Pty) Ltd',
    email: 'info@audiosure.co.za',
    phone: '+27 21 777 8888',
    contact_person: 'Audio Specialist',
    address: '630 Sure Street, Cape Town, Western Cape 8008',
    website: 'https://www.audiosure.co.za',
    tax_id: '9012345681',
    payment_terms: 'Net 30',
    primary_category: 'Audio Solutions',
    geographic_region: 'Western Cape',
    preferred_supplier: true,
    bee_level: 'Level 2',
    local_content_percentage: 75,
    status: 'active',
    performance_tier: 'tier_1',
    spend_last_12_months: '2650000.00',
    rating: '4.70'
  },
  {
    id: 'b2b2b2b2-b2b2-b2b2-b2b2-b2b2b2b2b2b2',
    name: 'ApexPro Distribution',
    supplier_code: 'APEXPR',
    company_name: 'ApexPro Distribution (Pty) Ltd',
    email: 'sales@apexpro.co.za',
    phone: '+27 11 999 0000',
    contact_person: 'Alex Apex',
    address: '741 Apex Tower, Johannesburg, Gauteng 2006',
    website: 'https://www.apexpro.co.za',
    tax_id: '9123456782',
    payment_terms: 'Net 30',
    primary_category: 'Pro Audio Distribution',
    geographic_region: 'Gauteng',
    preferred_supplier: true,
    bee_level: 'Level 1',
    local_content_percentage: 85,
    status: 'active',
    performance_tier: 'tier_1',
    spend_last_12_months: '3800000.00',
    rating: '4.80'
  }
]

async function insertSuppliers() {
  const client = await pool.connect()

  try {
    console.log('🗑️  Clearing existing suppliers...')
    await client.query('DELETE FROM suppliers')

    console.log('📦 Inserting 22 suppliers...')

    for (const supplier of suppliers) {
      await client.query(`
        INSERT INTO suppliers (
          id, name, supplier_code, company_name, email, phone, contact_person,
          address, website, tax_id, payment_terms, primary_category,
          geographic_region, preferred_supplier, bee_level, local_content_percentage,
          status, performance_tier, spend_last_12_months, rating,
          created_at, updated_at
        ) VALUES (
          $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16,
          $17, $18, $19, $20, NOW(), NOW()
        )
      `, [
        supplier.id, supplier.name, supplier.supplier_code, supplier.company_name,
        supplier.email, supplier.phone, supplier.contact_person, supplier.address,
        supplier.website, supplier.tax_id, supplier.payment_terms, supplier.primary_category,
        supplier.geographic_region, supplier.preferred_supplier, supplier.bee_level,
        supplier.local_content_percentage, supplier.status, supplier.performance_tier,
        supplier.spend_last_12_months, supplier.rating
      ])

      console.log(`✅ Inserted: ${supplier.name} (${supplier.supplier_code})`)
    }

    // Verify count
    const result = await client.query('SELECT COUNT(*) as count FROM suppliers')
    console.log(`\n🎉 Successfully inserted ${result.rows[0].count} suppliers!`)

    // Show summary
    const summary = await client.query(`
      SELECT
        COUNT(*) as total,
        COUNT(CASE WHEN preferred_supplier = true THEN 1 END) as preferred,
        COUNT(CASE WHEN performance_tier = 'tier_1' THEN 1 END) as tier1,
        COUNT(CASE WHEN performance_tier = 'tier_2' THEN 1 END) as tier2,
        COUNT(CASE WHEN performance_tier = 'tier_3' THEN 1 END) as tier3,
        ROUND(AVG(rating::numeric), 2) as avg_rating,
        SUM(spend_last_12_months::numeric) as total_spend
      FROM suppliers
    `)

    const stats = summary.rows[0]
    console.log('\n📊 SUPPLIER SUMMARY:')
    console.log(`Total Suppliers: ${stats.total}`)
    console.log(`Preferred Suppliers: ${stats.preferred}`)
    console.log(`Tier 1 (Strategic): ${stats.tier1}`)
    console.log(`Tier 2 (Preferred): ${stats.tier2}`)
    console.log(`Tier 3 (Approved): ${stats.tier3}`)
    console.log(`Average Rating: ${stats.avg_rating}`)
    console.log(`Total Annual Spend: R${new Intl.NumberFormat('en-ZA').format(stats.total_spend)}`)

  } catch (error) {
    console.error('❌ Error inserting suppliers:', error)
  } finally {
    client.release()
    await pool.end()
  }
}

insertSuppliers()